### ISSUE TITLE
plex sso: sso-functions.php: "Cannot access offset of type string on string"

### ISSUE THREAD

**Issue by felinira** [causefx/Organizr#1570]
###### Operating System: debian
<hr>

##### Problem Description:
Plex SSO fails with "API Connection failed"
The nginx logs show the following:
```
2021/01/30 22:30:41 [error] 280429#280429: *127352 FastCGI sent in stderr: "PHP message: Slim Application Error
Type: TypeError
Code: 0
Message: Cannot access offset of type string on string
File: /opt/git/Organizr/api/functions/sso-functions.php
Line: 13
Trace: #0 /opt/git/Organizr/api/functions/sso-functions.php(29): Organizr->getSSOUserFor()
#1 /opt/git/Organizr/api/classes/organizr.class.php(3181): Organizr->ssoCheck()
#2 /opt/git/Organizr/api/classes/organizr.class.php(3064): Organizr->authRegister()
#3 /opt/git/Organizr/api/v2/routes/login.php(4): Organizr->login()
#4 /opt/git/Organizr/api/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(43): {closure}()
#5 /opt/git/Organizr/api/vendor/slim/slim/Slim/Routing/Route.php(384): Slim\Handlers\Strategies\RequestResponse->__invoke()
#6 /opt/git/Organizr/api/vendor/slim/slim/Slim/MiddlewareDispatcher.php(81): Slim\Routing\Route->handle()
#7 /opt/git/Organizr/api/vendor/slim/slim/Slim/MiddlewareDispatcher.php(81): Slim\MiddlewareDispatcher->handle()
#8 /opt/git/Organizr/api/vendor/slim/slim/Slim/Routing/Route.ph" while reading response header from upstream, client: <redacted>, server: <redacted>, request: "POST /api/v2/login HTTP/1.1", upstream: "fastcgi://unix:/run/php/php8.0-fpm.sock:", host: "<redacted>", referrer: "https://<redacted>"
```
<hr>

##### Reproduction Steps:
* configure plex sso
* try to login with plex sso
<hr>

#### Errors on screen?  If so paste here:
```
API Connection failed
```

**Comment by causefx** [comment]
It is failing at Tautulli part. is that enables too?

**Comment by felinira** [comment]
Ah, right, I accidentally had that enabled and probably misconfigured. Disabling it worked. Thanks. I didn't think to look because the backend wasn't selected.

**Comment by causefx** [comment]
fixed the error now in dev... thanks for the report.
