### ISSUE TITLE
LDAP testing fails but configuration works

### ISSUE THREAD

**Issue by aniqueta** [causefx/Organizr#1683]
Version: 2.1.426
Branch: v2-master
Web server: nginx/1.21.1
PHP: 8.0.8
Operating System: macOS
<hr>

##### Problem Description:

LDAP testing leads to "API Error: Internal Server Error" however configuration works when logging in. (I spent hours trying to figure this what was incorrect in my configuration, before testing whether the error itself was wrong.) 

<hr>

##### Reproduction Steps:

1. Setup fresh OpenLDAP instance with basic users and groups
2. Setup Organizr per LDAP documentation (with either admin or read only service user) 

Relevant config.php

```
'authBackend' => 'ldap',
'authBackendDomain' => '',
'authBackendHost' => 'ldaps://sub.domain.tld:636',
'authBackendHostPrefix' => 'uid=',
'authBackendHostSuffix' => ',ou=People,dc=sub,dc=domain,dc=tld',
'authBaseDN' => 'uid=%s,ou=People,dc=sub,dc=domain,dc=tld',
'authDebug' => false,
'authProxyEnabled' => true,
'authProxyHeaderName' => 'X-Forwarded-User',
'authProxyHeaderNameEmail' => '',
'authProxyWhitelist' => '',
'authType' => 'external',
'ldapBindPassword' => 'deleted',
'ldapBindUsername' => 'cn=services,ou=People,dc=sub,dc=domain,dc=tld',
'ldapSSL' => true,
'ldapTLS' => false,
'ldapType' => '2',
```

3. Test login, receive error
4. Ignore error, but attempt login in fresh/private browser, login successful (with correct user/password)

<hr>

#### Errors on screen?  If so paste here:

As noted above, receive notification of API Error: Internal Server Error. Cannot find any further details in Organizr logs.

However, slapd logs show the following, which suggests that %s is not being replaced by the uid? 

```
conn=2008 fd=18 ACCEPT from IP=10.0.0.10:43523 (IP=0.0.0.0:636)
conn=2008 fd=18 TLS established tls_ssf=256 ssf=256
conn=2008 op=0 BIND dn="cn=services,ou=People,dc=sub,dc=domain,dc=tld" method=128
conn=2008 op=0 BIND dn="cn=services,ou=People,dc=sub,dc=domain,dc=tld" mech=SIMPLE ss>
conn=2008 op=0 RESULT tag=97 err=0 text=
conn=2008 op=1 BIND anonymous mech=implicit ssf=0
conn=2008 op=1 BIND dn="uid=testUser,ou=People,dc=sub,dc=domain,dc=tld" method=128
conn=2008 op=1 BIND dn="uid=testUser,ou=People,dc=sub,dc=domain,dc=tld" mech=SIMPLE ssf=0
conn=2008 op=1 RESULT tag=97 err=0 text=
conn=2008 op=2 SRCH base="uid=%s,ou=People,dc=sub,dc=domain,dc=tld" scope=2 deref=0 filter="(|(name=testUser)(mail=testUser)(uid=testUser)(sn=testUser)(givenName=testUser)(cn=testUser)(displayName=testUser))"
conn=2008 op=2 SRCH attr=*
conn=2008 op=2 SEARCH RESULT tag=101 err=32 nentries=0 text=
conn=2008 op=3 UNBIND
conn=2008 fd=18 closed
```

**Comment by causefx** [comment]
Was there anything in the webserver logs?

**Comment by aniqueta** [comment]
Thanks for the quick reply. Indeed there is something there, perhaps related to PHP 8?

```
[error] 353#0: *12485 FastCGI sent in stderr: "PHP message: Slim Application Error
Type: TypeError
Code: 0
Message: ldap_get_entries(): Argument #2 ($result) must be of type resource, bool given
File: /usr/local/var/www/organizr/api/vendor/adldap2/adldap2/src/Connections/Ldap.php
Line: 143
Trace: #0 /usr/local/var/www/organizr/api/vendor/adldap2/adldap2/src/Connections/Ldap.php(143): ldap_get_entries(Resource id #39, false)
#1 /usr/local/var/www/organizr/api/vendor/adldap2/adldap2/src/Query/Builder.php(600): Adldap\Connections\Ldap->getEntries(false)
#2 /usr/local/var/www/organizr/api/vendor/adldap2/adldap2/src/Query/Builder.php(385): Adldap\Query\Builder->parse(false)
#3 /usr/local/var/www/organizr/api/vendor/adldap2/adldap2/src/Query/Builder.php(394): Adldap\Query\Builder->Adldap\Query\{closure}()
#4 /usr/local/var/www/organizr/api/vendor/adldap2/adldap2/src/Query/Builder.php(271): Adldap\Query\Builder->query('(|(name=\\6b\\65\\...')
#5 /usr/local/var/www/organizr/api/vendor/adldap2/adldap2/src/Query/Builder.php(639): Adldap\Query\Builder->g" while reading response header from upstream, client: 10.0.0.42, server: organizr.domain.tld, request: "POST /api/v2/test/ldap/login HTTP/2.0", upstream: "fastcgi://unix:/usr/local/var/run/php/php8.0-fpm.sock:", host: "organizr.domain.tld"
```

**Comment by causefx** [comment]
You are correct.  I will keep an eye out for this issue:
https://github.com/Adldap2/Adldap2/issues/787

**Comment by aniqueta** [comment]
.

**Comment by aniqueta** [comment]
> You are correct. I will keep an eye out for this issue:
> [Adldap2/Adldap2#787](https://github.com/Adldap2/Adldap2/issues/787)

Looks like this is resolved now. Will you be updating Organizr, or do I need to do something on my end to use the new LDAP package? Thanks.

**Comment by causefx** [comment]
I will update and close

**Comment by causefx** [comment]
fixed in master
