### ISSUE TITLE
Error 500 after installing Organizr (master and develop branch) PHP Fatal error:  Uncaught Error: Call to a member function query() on null

### ISSUE THREAD

**Issue by megapearl** [causefx/Organizr#1686]
###### Operating System: FreeBSD 12.2-RELEASE-p7
<hr>

##### Problem Description:

Organizr is giving Error 500 Internal Error when browsing to it.

<hr>

##### Reproduction Steps:

root@fileserver:/usr/local/www/organizr # git clone -b v2-develop https://github.com/causefx/Organizr.git
<hr>

#### Errors on screen?  If so paste here:

```
PHP Fatal error:  Uncaught Error: Call to a member function query() on null in /usr/local/www/organizr/api/classes/organizr.class.php:6561\nStack trace:\n#0 /usr/local/www/organizr/api/classes/organizr.class.php(943): Organizr->processQueries()\n#1 /usr/local/www/organizr/api/classes/organizr.class.php(987): Organizr->getGuest()\n#2 /usr/local/www/organizr/api/classes/organizr.class.php(136): Organizr->guestUser()\n#3 /usr/local/www/organizr/index.php(3): Organizr->__construct()\n#4 {main}\n  thrown in /usr/local/www/organizr/api/classes/organizr.class.php on line 6561


At line 651 is:

        protected function processQueries(array $request, $migration = false)
        {
                $results = array();
                $firstKey = '';
                try {
                        foreach ($request as $k => $v) {

                                $query = ($migration) ? $this->otherDb->query($v['query']) : $this->db->query($v['query']);
                                $keyName = (isset($v['key'])) ? $v['key'] : $k;
                                $firstKey = (isset($v['key']) && $k == 0) ? $v['key'] : $k;
                                switch ($v['function']) {
                                        case 'fetchAll':
                                                $results[$keyName] = $query->fetchAll();
                                                break;
                                        case 'fetch':
                                                // PHP 8 Fix?
                                                $query->setRowClass(null);
                                                $results[$keyName] = $query->fetch();
                                                break;
                                        case 'getAffectedRows':
                                                $results[$keyName] = $query->getAffectedRows();
                                                break;
                                        case 'getRowCount':
                                                $results[$keyName] = $query->getRowCount();
                                                break;
                                        case 'fetchSingle':
                                                // PHP 8 Fix?
                                                $query->setRowClass(null);
                                                $results[$keyName] = $query->fetchSingle();
                                                break;
                                        case 'query':
                                                $results[$keyName] = $query;
                                                break;
                                        default:
                                                return false;
                                }
                        }

                } 
```

**Comment by HalianElf** [comment]
Looks like you're missing/don't have the sqlite php module enabled.

**Comment by megapearl** [comment]
You're right, that was the fix! thanks!
