### ISSUE TITLE
blank screen with latest dev update

### ISSUE THREAD

**Issue by SkalCore** [causefx/Organizr#1734]
###### Operating System:5.10.60-qnap  x86_64 GNU/Linux /docker
<hr>

##### Problem Description:
after last dev update, webserver failure, restarting docker, after that only white page is shown

<hr>

##### Reproduction Steps:
stop docker, remove image, pull new image, starting image, same error

<hr>

#### Errors on screen?  If so paste here:

```
Type: ParseError
Code: 0
Message: syntax error, unexpected ']'
File: /config/www/organizr/api/config/config.php
Line: 418
Trace: #0 /config/www/organizr/api/classes/organizr.class.php(1013): Organizr->{closure}()
#1 /config/www/organizr/api/classes/organizr.class.php(1053): Organizr->loadConfig()
#2 /config/www/organizr/api/classes/organizr.class.php(127): Organizr->config()
#3 /config/www/organizr/api/plugins/chat/api.php(142): Organizr->__construct()
#4 /config/www/organizr/api/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(43): {closure}()
#5 /config/www/organizr/api/vendor/slim/slim/Slim/Routing/Route.php(384): Slim\Handlers\Strategies\RequestResponse->__invoke()
#6 /config/www/organizr/api/vendor/slim/slim/Slim/MiddlewareDispatcher.php(81): Slim\Routing\Route->handle()
#7 /config/www/organizr/api/vendor/slim/slim/Slim/MiddlewareDispatcher.php(81): Slim\MiddlewareDispatcher->handle()
#8 /config/www/organizr/api/vendor/slim/slim/Slim/Routing/Ro" while reading response header from upstream, client: 192.168.90.254, server: _, request: "GET /api/v2/plugins/chat/message HTTP/1.1", upstream: "fastcgi://unix:/var/run/php7-fpm.sock:", host: "organizr.shadedesk.org", referrer: "https://organizr.shadedesk.org/"

```

**Comment by causefx** [comment]
this was entirely my fault.

1. Stop container.
2. Edit `/config/www/organizr/api/config.php`
3. find this entry
```
'installedPlugins' => [
        '' => [
            'name' => '',
            'repo' => 'https://github.com/Organizr/Organizr-Plugins',
            'version' => 
        ]
    ],
```

4. delete that entire entry
5. restart container
6. profit

**Comment by SkalCore** [comment]
ok thanks, it works again as before

**Comment by causefx** [comment]
so sorry about that, i just added in another check to find if it happens again.
