### ISSUE TITLE
PHP Fatal Error: Nekonomokochan\PhpJsonLogger\Logger::debug() must be of the type array, string given

### ISSUE THREAD

**Issue by jtessler** [causefx/Organizr#1737]
###### Operating System: Docker/Debian (ghcr.io/organizr/organizr:latest)
<hr>

##### Problem Description:
Server returns 500 on any request. NGINX logs show `PHP Fatal Error` when calling `Nekonomokochan\PhpJsonLogger\Logger->debug()`

<hr>

##### Reproduction Steps:
1. Start docker container
2. Load `/` endpoint

<hr>

##### Notes

Seems related to the recent logging commit: https://github.com/causefx/Organizr/commit/daa94845c0e409682ea346e424a6f2c9623a4a60

<hr>

#### Errors on screen?  If so paste here:
Chrome:
```
This page isn’t working
<hostname-removed> is currently unable to handle this request.
HTTP ERROR 500
```

/config/log/nginx/error.log (snippet)
```
2021/10/17 19:04:22 [error] 371#371: *12 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught TypeError: Argument 2 passed to Nekonomokochan\PhpJsonLogger\Logger::debug() must be of the type array, string given, called in /config/www/organizr/api/classes/organizr.class.php on line 1292 and defined in /config/www/organizr/api/vendor/nekonomokochan/php-json-logger/src/PhpJsonLogger/Logger.php:72
Stack trace:
#0 /config/www/organizr/api/classes/organizr.class.php(1292): Nekonomokochan\PhpJsonLogger\Logger->debug()
#1 /config/www/organizr/api/classes/organizr.class.php(222): Organizr->validateToken()
#2 /config/www/organizr/api/classes/organizr.class.php(214): Organizr->checkUserTokenForValidation()
#3 /config/www/organizr/api/classes/organizr.class.php(150): Organizr->setCurrentUser()
#4 /config/www/organizr/index.php(3): Organizr->__construct()
#5 {main}
thrown in /config/www/organizr/api/vendor/nekonomokochan/php-json-logger/src/PhpJsonLogger/Logger.php on line 72" while reading response header from upstream, client: <IP-removed>, server: _, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/var/run/php7-fpm.sock:", host: "<hostname-removed>", referrer: "<referrer-url-removed>"
```

Docker logs:
```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 10-adduser: executing... 

-------------------------------------
GID/UID
-------------------------------------
User uid:    1000
User gid:    1000
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 20-config: executing... 
[cont-init.d] 20-config: exited 0.
[cont-init.d] 30-setup: executing... 
[cont-init.d] 30-setup: exited 0.
[cont-init.d] 40-install: executing... 
-----------------------
|  Updating Organizr  |
-----------------------
HEAD is now at a9a22244 Merge pull request #1735 from causefx/v2-develop
Already on 'v2-master'
Your branch is up to date with 'origin/v2-master'.
HEAD is now at a9a22244 Merge pull request #1735 from causefx/v2-develop
Already up to date.
[cont-init.d] 40-install: exited 0.
[cont-init.d] 50-debug: executing... 
-----------------------
|     Kernel Info     |
-----------------------
Linux organizr-675dd5d7f-2fvgw 4.19.0-17-amd64 #1 SMP Debian 4.19.194-2 (2021-06-21) x86_64 GNU/Linux
Time Zone: Etc/UTC
[cont-init.d] 50-debug: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
```

**Comment by jtessler** [comment]
Current workaround:

1. Rewind git repo (`/config/www/organizer`) back to the commit before `php-json-logger` was introduced: 19b7b1e
```
git reset --hard 19b7b1e70d3dc94a63451008db2737eaaddf8cbf~1
```

2. Disable auto-updates (using the `branch=manual` environment variable)

Note: reverting just the suspicious commit daa9484 was not enough

**Comment by causefx** [comment]
good catch. i will fix that and add some validation on those variables…

it seems $token is a string.

**Comment by jtessler** [comment]
Thanks, @causefx! :+1:

**Comment by causefx** [comment]
temp fix is in dev branch

**Comment by causefx** [comment]
push is now live in master

**Comment by jtessler** [comment]
Verified everything's working again at f434bdf2. Appreciate the quick help!

**Comment by causefx** [comment]
thanks for reporting it :)
