### ISSUE TITLE
"Cannot access offset of type string on string" in sso-functions.php

### ISSUE THREAD

**Issue by Kyle-B** [causefx/Organizr#1769]
###### Operating System: Arch
<hr>

##### Problem Description:
Very similar to #1570

Hits for new users when using Authelia+LDAP, with the Auth Proxy option turned on. This flow was working until semi-recently? Not exactly sure when it broke because old user accounts (that presumably had their Organizr internal user created) continue to work. Authentication type is set to OrganizrDB + Backend (LDAP).

Edit: 4cd3022d66f6fbbd9cddd1c301958cd3a47ba7df looks like the immediate cause.

A quick fix that worked for me is:
```
$username = (gettype($userobj) == 'string') ? $userobj : $userobj['username'];
$this->setLoggerChannel('Authentication', $username);
```
But I'm not sure if multiple gettype calls is really the best way to go about it.

##### Reproduction Steps:
Using Authelia for login + LDAP backend, create a new user and sign in. Successful login to Authelia will not lead to a successful login in Organzir.

<hr>

#### Errors on screen?  If so paste here:

```
2021/12/11 13:51:42 [error] 4085121#4085121: *307 FastCGI sent in stderr: "PHP message: Slim Application Error
Type: TypeError
Code: 0
Message: Cannot access offset of type string on string
File: /var/lib/organizr/api/functions/sso-functions.php
Line: 41
Trace: #0 /var/lib/organizr/api/classes/organizr.class.php(3036): Organizr->ssoCheck()
#1 /var/lib/organizr/api/classes/organizr.class.php(2909): Organizr->authRegister()
#2 /var/lib/organizr/api/v2/routes/login.php(4): Organizr->login()
#3 /var/lib/organizr/api/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(43): {closure}()
#4 /var/lib/organizr/api/vendor/slim/slim/Slim/Routing/Route.php(384): Slim\Handlers\Strategies\RequestResponse->__invoke()
#5 /var/lib/organizr/api/vendor/slim/slim/Slim/MiddlewareDispatcher.php(81): Slim\Routing\Route->handle()
#6 /var/lib/organizr/api/vendor/slim/slim/Slim/MiddlewareDispatcher.php(81): Slim\MiddlewareDispatcher->handle()
#7 /var/lib/organizr/api/vendor/slim/slim/Slim/Routing/Route.php(341): Slim\MiddlewareDispatcher->handle()
#8 /var/lib/organizr/api/vendor/slim/sli" while reading response header from upstream, client: 127.0.0.1, server: 127.0.0.1, request: "POST /api/v2/login HTTP/1.1", upstream: "fastcgi://unix:/run/php-fpm/php-fpm.sock:", host: "********", referrer: "https://**********/"
```

**Comment by causefx** [comment]
thanks for this.  I will look into it tomorrow morning.

**Comment by causefx** [comment]
fixed in dev
