### ISSUE TITLE
iCal does not show calendar items, Unknown or bad timezone (W. Europe Standard Time)

### ISSUE THREAD

**Issue by RoL0NL** [causefx/Organizr#1772]
###### Operating System: Debian (Docker, organizr/organizr:latest image from hub.docker.com)
<hr>

##### Problem Description:
Multiple ical calendars (subscription links from Nextcloud calendars) are added to the iCal homepage item. On the homepage, the calendar is empty. In the log (see below) a 'bad timezone' error is given.

<hr>

##### Reproduction Steps:
  - Activate iCal homepage item, add Nextcloud calendar subscription link.
  - Refresh page, go to homepage
  - Calendar is empty (.ical link is not!)
  - Timezone error in nginx log

<hr>

#### Errors on screen?  If so paste here:

```
2021/12/23 08:57:53 [error] 23872#23872: *50398 FastCGI sent in stderr: "PHP message: Slim Application Error
Type: Exception
Code: 0
Message: DateTimeZone::__construct(): Unknown or bad timezone (W. Europe Standard Time)
File: /config/www/organizr/api/homepage/ical.php
Line: 245
Trace: #0 /config/www/organizr/api/homepage/ical.php(245): DateTimeZone->__construct()
#1 /config/www/organizr/api/homepage/calendar.php(119): Organizr->getICalendar()
#2 /config/www/organizr/api/v2/routes/homepage.php(13): Organizr->getCalendar()
#3 /config/www/organizr/api/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(43): {closure}()
#4 /config/www/organizr/api/vendor/slim/slim/Slim/Routing/Route.php(384): Slim\Handlers\Strategies\RequestResponse->__invoke()
#5 /config/www/organizr/api/vendor/slim/slim/Slim/MiddlewareDispatcher.php(81): Slim\Routing\Route->handle()
#6 /config/www/organizr/api/vendor/slim/slim/Slim/MiddlewareDispatcher.php(81): Slim\MiddlewareDispatcher->handle()
#7 /config/www/organizr/api/vendor/slim/slim/Slim/Routing/Route.php(341): Slim\MiddlewareDispatche" while reading response header from upstr
```

Beginning of my .ical file:
```
BEGIN:VCALENDAR
VERSION:2.0
CALSCALE:GREGORIAN
PRODID:-//SabreDAV//SabreDAV//EN
X-WR-CALNAME:Robin (rlohuis)
X-APPLE-CALENDAR-COLOR:#007AFF
REFRESH-INTERVAL;VALUE=DURATION:PT4H
X-PUBLISHED-TTL:PT4H
BEGIN:VTIMEZONE
TZID:W. Europe Standard Time
BEGIN:STANDARD
DTSTART:19701025T030000
RRULE:FREQ=YEARLY;BYDAY=-1SU;BYHOUR=3;BYMINUTE=0;BYMONTH=10
TZNAME:W. Europe Standard Time
TZOFFSETFROM:+0200
TZOFFSETTO:+0100
END:STANDARD
BEGIN:DAYLIGHT
DTSTART:19700329T020000
RRULE:FREQ=YEARLY;BYDAY=-1SU;BYHOUR=2;BYMINUTE=0;BYMONTH=3
TZNAME:W. Europe Daylight Time
TZOFFSETFROM:+0100
TZOFFSETTO:+0200
END:DAYLIGHT
END:VTIMEZONE
BEGIN:VTIMEZONE
TZID:Europe/Amsterdam
BEGIN:DAYLIGHT
TZOFFSETFROM:+0100
TZOFFSETTO:+0200
TZNAME:CEST
DTSTART:19700329T020000
RRULE:FREQ=YEARLY;BYMONTH=3;BYDAY=-1SU
END:DAYLIGHT
BEGIN:STANDARD
TZOFFSETFROM:+0200
TZOFFSETTO:+0100
TZNAME:CET
DTSTART:19701025T030000
RRULE:FREQ=YEARLY;BYMONTH=10;BYDAY=-1SU
END:STANDARD
END:VTIMEZONE
```
example event;
```
BEGIN:VEVENT
CLASS:PUBLIC
DTEND;TZID=W. Europe Standard Time:20210418T180000
DTSTAMP:20210419T065129Z
DTSTART;TZID=W. Europe Standard Time:20210418T100000
LOCATION:x
PRIORITY:5
SEQUENCE:0
SUMMARY:x
TRANSP:OPAQUE
UID:xxxxxxxxxxxxxxxxxxxxx
X-MICROSOFT-CDO-BUSYSTATUS:BUSY
END:VEVENT
```

**Comment by jessehickman** [comment]
The quick answer is "W. Europe Standard Time" isnt supported.

Longer answer, this is an issue with the following line in ical.php:

`$originalTimeZone = $this->calendarStandardizeTimezone($originalTimeZone);`

Previously it parsed any line with "TZID=" to grab the time zone which is "W. Europe Standard Time" and that isn't covered in the standardizing of time zones.

I added it in https://github.com/causefx/Organizr/pull/1775 however a more comprehensive directory of timezone conversions may be in order.

**Comment by causefx** [comment]
fixed.
