### ISSUE TITLE
Error 500 on page load

### ISSUE THREAD

**Issue by G4Zz0L1** [causefx/Organizr#1835]
###### Operating System: Arch Linux
```
PHP 8.1.5 (cli) (built: Apr 14 2022 18:36:20) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.5, Copyright (c) Zend Technologies
    with Zend OPcache v8.1.5, Copyright (c), by Zend Technologies
    with Xdebug v3.1.2, Copyright (c) 2002-2021, by Derick Rethans
```
<hr>

##### Problem Description:

New error on the apache error log, from the last version. If you need more info let me know.
<hr>

#### Errors on screen?  If so paste here:

```
AH01071: Got error 'PHP message: Organizr E_DEPRECATED:  Return type of Ramsey\\Uuid\\Uuid::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /srv/http/organizr/api/vendor/ramsey/uuid/src/Uuid.php on line 216
PHP message: PHP Fatal error:  During inheritance of JsonSerializable: Uncaught Error: Class "Ramsey\\Uuid\\Uuid" not found in /srv/http/organizr/api/vendor/nekonomokochan/php-json-logger/src/PhpJsonLogger/JsonFormatter.php:62
Stack trace:
#0 /srv/http/organizr/api/vendor/nekonomokochan/php-json-logger/src/PhpJsonLogger/JsonFormatter.php(26): Nekonomokochan\\PhpJsonLogger\\JsonFormatter->generateUuid()
#1 /srv/http/organizr/api/vendor/monolog/monolog/src/Monolog/Handler/AbstractProcessingHandler.php(37): Nekonomokochan\\PhpJsonLogger\\JsonFormatter->format()
#2 /srv/http/organizr/api/vendor/monolog/monolog/src/Monolog/Logger.php(344): Monolog\\Handler\\AbstractProcessingHandler->handle()
#3 /srv/http/organizr/api/vendor/monolog/monolog/src/Monolog/Logger.php(446): Monolog\\Logger->addRecord()
#4 /srv/http/organizr/api/vendor/nekonomokochan/php-json-logger/src/PhpJsonLogger/Logger.php(105): Monolog\\Logger->addWarning()
#5 /srv/http/organizr/api/classes/organizr.class.php(859): Nekonomokochan\\PhpJsonLogger\\L...'
```

**Comment by causefx** [comment]
ATM I can't do anything about that until Ramsey\Uuid fixes it for 8.1

**Comment by mariusberget92** [comment]
Same. But I don't think Ramsey\Uuid is the problem. That package is already updated to work with PHP 8.0+ in Uuid 4.3.0 as far as I can see. Looks like the problem is this package: nekonomokochan/php-json-logger, wich uses older version of the Uuid (?)

**Comment by G4Zz0L1** [comment]
And it's not updated from 2019, as per its github.
Maybe it should be changed to something newer?

**Comment by mariusberget92** [comment]
> And it's not updated from 2019, as per its github. Maybe it should be changed to something newer?

Indeed. Doesn't look like the package is going to get an update.

**Comment by causefx** [comment]
try latest dev branch and see if any errors on php 8.1

**Comment by G4Zz0L1** [comment]
It seems to work now, both web and cron, without errors.
Thanks!

**Comment by causefx** [comment]
sweet! thanks!
