### ISSUE TITLE
news - error

### ISSUE THREAD

**Issue by stanthewizzard** [causefx/Organizr#1840]
###### PHP; 8.1.2

<hr>

##### Problem Description:
After upgrade to 22.04
when opening Organizr there is a small pop-up (where login is used to be) with News error

Thanks for help

**Comment by causefx** [comment]
can you share a screenshot or error?

**Comment by stanthewizzard** [comment]
![B8AE022B-E000-4C5F-B3A2-8B7C69ED9F83](https://user-images.githubusercontent.com/1823450/170095419-1a08b26e-d459-4cda-a9f9-7829117667f5.jpeg)

here you are
Thanks

**Comment by causefx** [comment]
When that happens can you check browser console for any error?

Also, are you able to go these urls:

```
http://org-url/api/v2/news
http://org-url/api/v2/plugins/marketplace
```

If so - what are the outputs?

**Comment by stanthewizzard** [comment]
{
    "response": {
        "result": "success",
        "message": null,
        "data": [
            11,
            10,
            9,
            12,
            13,
            15
        ]
    }
}



Bad gateway on the 2nd URL

**Comment by causefx** [comment]
Do you have any custom plugin URLs in marketplace?

**Comment by stanthewizzard** [comment]
None

**Comment by stanthewizzard** [comment]
On marketplace
I got 
Copy json failed
Error

**Comment by causefx** [comment]
are you able to check your webserver logs?

**Comment by stanthewizzard** [comment]
this one
```
2022/05/25 07:46:15 [error] 49430#49430: *1 FastCGI sent in stderr: "PHP message: Organizr E_DEPRECATED:  Return type of Lcobucci\JWT\Claim\Basic::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /opt/Organizr/api/vendor/lcobucci/jwt/src/Claim/Basic.php on line 63" while reading response header from upstream, client: 192.168.0.180, server: grabbing3.xxxxxx.com, request: "GET / HTTP/2.0", upstream: "fastcgi://unix:/run/php/php-fpm.sock:", host: "grabbing3.xxxxxx.com"
2022/05/25 07:46:20 [error] 49430#49430: *1 FastCGI sent in stderr: "PHP message: Organizr E_DEPRECATED:  Return type of Lcobucci\JWT\Claim\Basic::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /opt/Organizr/api/vendor/lcobucci/jwt/src/Claim/Basic.php on line 63PHP message: Organizr E_DEPRECATED:  Return type of Ramsey\Uuid\Uuid::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /opt/Organizr/api/vendor/ramsey/uuid/src/Uuid.php on line 216PHP message: Organizr E_DEPRECATED:  Return type of Requests_Cookie_Jar::offsetExists($key) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /opt/Organizr/api/vendor/rmccue/requests/library/Requests/Cookie/Jar.php on line 63PHP message: Organizr E_DEPRECATED:  Return type of Requests_Cookie_Jar::offsetGet($key) should either be compatible with ArrayAccess::offsetGet(mixed $offset): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /opt/Organizr/api/vendor/rmccue/requests/library/Requests/Cookie/Jar.php on line 73PHP message: Organizr E_DEPRECATED:  Return type of Requests_Cookie_Jar::offsetSet($key, $value) should either be compatible with ArrayAccess::offsetSet(mixed $offset, mixed $value): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /opt/Organizr/api/vendor/rmccue/requests/library/Requests/Cookie/Jar.php on line 89PHP message: Organizr E_DEPRECATED:  Return type of Requests_Cookie_Jar::offsetUnset($key) should either be compatible with ArrayAccess::offsetUnset(mixed $offset): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in
2022/05/25 07:46:20 [error] 49430#49430: *1 FastCGI sent in stderr: "veDictionary::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /opt/Organizr/api/vendor/rmccue/requests/library/Requests/Utility/CaseInsensitiveDictionary.php on line 91PHP message: Organizr E_DEPRECATED:  Implicit conversion from float 0.20400595664978027 to int loses precision in /opt/Organizr/api/functions/normal-functions.php on line 12" while reading response header from upstream, client: 192.168.0.180, server: grabbing3.xxxxxx.com, request: "POST /api/v2/login HTTP/2.0", upstream: "fastcgi://unix:/run/php/php-fpm.sock:", host: "grabbing3.xxxxxx.com", referrer: "https://grabbing3.xxxxxx.com/"
2022/05/25 07:46:20 [error] 49430#49430: *1 FastCGI sent in stderr: "PHP message: Organizr E_DEPRECATED:  Return type of Lcobucci\JWT\Claim\Basic::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /opt/Organizr/api/vendor/lcobucci/jwt/src/Claim/Basic.php on line 63" while reading response header from upstream, client: 192.168.0.180, server: grabbing3.xxxxxx.com, request: "GET / HTTP/2.0", upstream: "fastcgi://unix:/run/php/php-fpm.sock:", host: "grabbing3.xxxxxx.com", referrer: "https://grabbing3.xxxxxx.com/"
2022/05/25 07:46:21 [error] 49430#49430: *1 FastCGI sent in stderr: "PHP message: Organizr E_DEPRECATED:  Return type of Lcobucci\JWT\Claim\Basic::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /opt/Organizr/api/vendor/lcobucci/jwt/src/Claim/Basic.php on line 63PHP message: Organizr E_DEPRECATED:  strtr(): Passing null to parameter #1 ($string) of type string is deprecated in /opt/Organizr/api/functions/organizr-functions.php on line 799" while reading response header from upstream, client: 192.168.0.180, server: grabbing3.xxxxxx.com, request: "GET /api/v2/launch HTTP/2.0", upstream: "fastcgi://unix:/run/php/php-fpm.sock:", host: "grabbing3.xxxxxx.com", referrer: "https://grabbing3.xxxxxx.com/"
2022/05/25 07:46:21 [error] 49430#49430: *1 FastCGI sent in stderr: "PHP message: Organizr E_DEPRECATED:  Return type of Lcobucci\JWT\Claim\Basic::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /opt/Organizr/api/vendor/lcobucci/jwt/src/Claim/Basic.php on line 63PHP message: Organizr E_DEPRECATED:  Return type of Ramsey\Uuid\Uuid::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /opt/Organizr/api/vendor/ramsey/uuid/src/Uuid.php on line 216" while reading response header from upstream, client: 192.168.0.180, server: grabbing3.xxxxxx.com, request: "GET /api/v2/page/settings HTTP/2.0", upstream: "fastcgi://unix:/run/php/php-fpm.sock:", host: "grabbing3.xxxxxx.com", referrer: "https://grabbing3.xxxxxx.com/"
2022/05/25 07:46:21 [error] 49430#49430: *1 FastCGI sent in stderr: "PHP message: Organizr E_DEPRECATED:  Return type of Lcobucci\JWT\Claim\Basic::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /opt/Organizr/api/vendor/lcobucci/jwt/src/Claim/Basic.php on line 63PHP message: Organizr E_DEPRECATED:  Return type of Requests_Cookie_Jar::offsetExists($key) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /opt/Organizr/api/vendor/rmccue/requests/library/Requests/Cookie/Jar.php on line 63PHP message: Organizr E_DEPRECATED:  Return type of Requests_Cookie_Jar::offsetGet($key) should either be compatible with ArrayAccess::offsetGet(mixed $offset): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /opt/Organizr/api/vendor/rmccue/requests/library/Requests/Cookie/Jar.php on line 73PHP message: Organizr E_DEPRECATED:  Return type of Requests_Cookie_Jar::offsetSet($key, $value) should either be compatible with ArrayAccess::offsetSet(mixed $offset, mixed $value): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /opt/Organizr/api/vendor/rmccue/requests/library/Requests/Cookie/Jar.php on line 89PHP message: Organizr E_DEPRECATED:  Return type of Requests_Cookie_Jar::offsetUnset($key) should either be compatible with ArrayAccess::offsetUnset(mixed $offset): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /opt/Organizr/api/vendor/rmccue/requests/library/Requests/Cookie/Jar.php on line 102PHP message: Organizr E_DEPRECATED:  Return type of Requests_Cookie_Jar::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\ReturnTypeWillChange] attribute should be used to tempo
2022/05/25 07:46:21 [error] 49430#49430: *1 upstream sent too big header while reading response header from upstream, client: 192.168.0.180, server: grabbing3.xxxxxx.com, request: "GET /api/v2/plugins/marketplace HTTP/2.0", upstream: "fastcgi://unix:/run/php/php-fpm.sock:", host: "grabbing3.xxxxxx.com", referrer: "https://grabbing3.xxxxxx.com/"
2022/05/25 07:46:22 [error] 49430#49430: *1 FastCGI sent in stderr: "PHP message: Organizr E_DEPRECATED:  Return type of Lcobucci\JWT\Claim\Basic::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /opt/Organizr/api/vendor/lcobucci/jwt/src/Claim/Basic.php on line 63PHP message: Organizr E_DEPRECATED:  Return type of Requests_Cookie_Jar::offsetExists($key) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /opt/Organizr/api/vendor/rmccue/requests/library/Requests/Cookie/Jar.php on line 63PHP message: Organizr E_DEPRECATED:  Return type of Requests_Cookie_Jar::offsetGet($key) should either be compatible with ArrayAccess::offsetGet(mixed $offset): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /opt/Organizr/api/vendor/rmccue/requests/library/Requests/Cookie/Jar.php on line 73PHP message: Organizr E_DEPRECATED:  Return type of Requests_Cookie_Jar::offsetSet($key, $value) should either be compatible with ArrayAccess::offsetSet(mixed $offset, mixed $value): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /opt/Organizr/api/vendor/rmccue/requests/library/Requests/Cookie/Jar.php on line 89PHP message: Organizr E_DEPRECATED:  Return type of Requests_Cookie_Jar::offsetUnset($key) should either be compatible with ArrayAccess::offsetUnset(mixed $offset): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /opt/Organizr/api/vendor/rmccue/requests/library/Requests/Cookie/Jar.php on line 102PHP message: Organizr E_DEPRECATED:  Return type of Requests_Cookie_Jar::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\ReturnTypeWillChange] attribute should be used to tempo
2022/05/25 07:46:22 [error] 49430#49430: *1 FastCGI sent in stderr: "age: Organizr E_NOTICE:  iconv_strpos(): Detected an illegal character in input string in /opt/Organizr/api/vendor/symfony/polyfill-mbstring/Mbstring.php on line 511PHP message: Slim Application Error
Type: Error
Code: 0
Message: Call to undefined function mb_regex_encoding()
File: /opt/Organizr/api/vendor/paquettg/php-html-parser/src/PHPHtmlParser/Dom/Cleaner.php
Line: 124
Trace: #0 /opt/Organizr/api/vendor/paquettg/php-html-parser/src/PHPHtmlParser/Dom/Cleaner.php(35): PHPHtmlParser\Dom\Cleaner->setUpRegexEncoding()
#1 /opt/Organizr/api/vendor/paquettg/php-html-parser/src/PHPHtmlParser/Dom.php(155): PHPHtmlParser\Dom\Cleaner->clean()
#2 /opt/Organizr/api/classes/organizr.class.php(5859): PHPHtmlParser\Dom->loadStr()
#3 /opt/Organizr/api/classes/organizr.class.php(5892): Organizr->getGithubSponsors()
#4 /opt/Organizr/api/v2/routes/sponsors.php(20): Organizr->getAllSponsors()
#5 /opt/Organizr/api/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(43): {closure}()
#6 /opt/Organizr/api/vendor/slim/slim/Slim/Routing/Route.php(384): Slim\Handlers\Strategies\RequestResponse->__invoke()
#7 /opt/Organizr/api/vendor/slim/slim/Slim/MiddlewareDispatcher.php(" while reading response header from upstream, client: 192.168.0.180, server: grabbing3.xxxx.com, request: "GET /api/v2/sponsors/all HTTP/2.0", upstream: "fastcgi://unix:/run/php/php-fpm.sock:", host: "grabbing3.xxx.com", referrer: "https://grabbing3.xxxx.com/"
2022/05/25 07:46:22 [error] 49430#49430: *1 FastCGI sent in stderr: "PHP message: Organizr E_DEPRECATED:  Return type of Lcobucci\JWT\Claim\Basic::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /opt/Organizr/api/vendor/lcobucci/jwt/src/Claim/Basic.php on line 63" while reading response header from upstream, client: 192.168.0.180, server: grabbing3.xxxx.com, request: "GET /api/v2/news HTTP/2.0", upstream: "fastcgi://unix:/run/php/php-fpm.sock:", host: "grabbing3.xxx.com", referrer: "https://grabbing3.xxx.com/"
```

**Comment by stanthewizzard** [comment]
I did a cookie and cache cleanup
error is gone

**Comment by stanthewizzard** [comment]
Any idea what’s happening ?

**Comment by causefx** [comment]
it's a php 8.1 issue - it may be solved in dev branch.  I should be merging to master tomorrow.

**Comment by stanthewizzard** [comment]
Awesome thanks

**Comment by causefx** [comment]
pushed to master now, you can let me know how it goes.

**Comment by stanthewizzard** [comment]
yes it works perfectly
Thank you :)
