### ISSUE TITLE
"Slim Application Error" after starting the Docker container

### ISSUE THREAD

**Issue by alesnav** [causefx/Organizr#1960]
###### Operating System: Docker organizr/organizr:latest
<hr>

##### Problem Description:

When starting the container, it does run without any error on Docker logs and it updates to the last git commit as expected. But when I try to open the webpage, it shows an error related to "Webserver Error: Slim Application Error" and it doesn't let me going further that point.
<hr>

##### Reproduction Steps:

Just starting the container, no more steps needed. My container has been running for several months but it does not work anymore since almost one month, showing this error.
<hr>

#### Errors on screen?  If so paste here:

![image](https://github.com/causefx/Organizr/assets/1645707/2bae22f7-fa3d-46e1-b968-40d67793f0cc)

Copying here in plane text, by extracting these lines directly from `/log/nginx/error.log`
```
2024/01/05 22:46:30 [error] 395#395: *528 FastCGI sent in stderr: "PHP message: Slim Application Error
Type: TypeError
Code: 0
Message: array_map(): Argument #2 ($array) must be of type array, null given
File: /config/www/organizr/api/classes/organizr.class.php
Line: 4213
Trace: #0 /config/www/organizr/api/classes/organizr.class.php(4213): array_map()
#1 /config/www/organizr/api/v2/routes/root.php(68): Organizr->getUserTabsAndCategories()
#2 /config/www/organizr/api/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(43): {closure}()
#3 /config/www/organizr/api/vendor/slim/slim/Slim/Routing/Route.php(384): Slim\Handlers\Strategies\RequestResponse->__invoke()
#4 /config/www/organizr/api/vendor/slim/slim/Slim/MiddlewareDispatcher.php(81): Slim\Routing\Route->handle()
#5 /config/www/organizr/api/vendor/slim/slim/Slim/MiddlewareDispatcher.php(81): Slim\MiddlewareDispatcher->handle()
#6 /config/www/organizr/api/vendor/slim/slim/Slim/Routing/Route.php(341): Slim\MiddlewareDispatcher->handle()
#7 /config/www/organizr/api/vendor/slim/slim/Slim/Routing/RouteRunn" while reading response header from upstream, client: 10.100.80.100, server: _, request: "GET /api/v2/launch HTTP/1.1", upstream: "fastcgi://unix:/var/run/php8-fpm.sock:"
```

**Comment by causefx** [comment]
this an upgraded install or new install?
Nvm, just saw you saidm ran fine before...

**Comment by alesnav** [comment]
It is an upgraded run, that was initially installed on the very beggining of v2.

**Comment by causefx** [comment]
are you able to open your db manually to see if there are tabs listed?

**Comment by alesnav** [comment]
I have tried to do it, and have located dDB logs file that maybe can help in the tshoot process

File `/www/db/logs/organizr-2024-01-05.log`:

```
{"log_level":"CRITICAL","message":"Dibi\\DriverException","channel":"Database","username":"Guest","trace_id":"783b09cc-9336-42f4-9de6-baec7665776e","file":"/config/www/organizr/api/classes/organizr.class.php","line":7914,"context":["SELECT * FROM tabs WHERE `add_to_admin` = 1 AND `enabled` = 1 ORDER BY `order` DESC"],"remote_ip_address":"10.255.0.2","server_ip_address":"10.100.80.113","user_agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36 Edg/120.0.0.0","datetime":"2024-01-05 21:58:09.106189","timezone":"UTC","process_time":70.98507881164551,"errors":{"message":"no such column: add_to_admin","code":1,"file":"/config/www/organizr/api/vendor/dibi/dibi/src/Dibi/Drivers/SqliteDriver.php","line":103,"trace":["#0 /config/www/organizr/api/vendor/dibi/dibi/src/Dibi/Drivers/SqliteDriver.php(90): Dibi\\Drivers\\SqliteDriver::createException()","#1 /config/www/organizr/api/vendor/dibi/dibi/src/Dibi/Connection.php(288): Dibi\\Drivers\\SqliteDriver->query()","#2 /config/www/organizr/api/vendor/dibi/dibi/src/Dibi/Connection.php(223): Dibi\\Connection->nativeQuery()","#3 /config/www/organizr/api/classes/organizr.class.php(7883): Dibi\\Connection->query()","#4 /config/www/organizr/api/classes/organizr.class.php(4178): Organizr->processQueries()","#5 /config/www/organizr/api/v2/routes/root.php(68): Organizr->getUserTabsAndCategories()","#6 /config/www/organizr/api/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(43): {closure}()","#7 /config/www/organizr/api/vendor/slim/slim/Slim/Routing/Route.php(384): Slim\\Handlers\\Strategies\\RequestResponse->__invoke()","#8 /config/www/organizr/api/vendor/slim/slim/Slim/MiddlewareDispatcher.php(81): Slim\\Routing\\Route->handle()","#9 /config/www/organizr/api/vendor/slim/slim/Slim/MiddlewareDispatcher.php(81): Slim\\MiddlewareDispatcher->handle()","#10 /config/www/organizr/api/vendor/slim/slim/Slim/Routing/Route.php(341): Slim\\MiddlewareDispatcher->handle()","#11 /config/www/organizr/api/vendor/slim/slim/Slim/Routing/RouteRunner.php(84): Slim\\Routing\\Route->run()","#12 /config/www/organizr/api/vendor/slim/slim/Slim/Middleware/RoutingMiddleware.php(59): Slim\\Routing\\RouteRunner->handle()","#13 /config/www/organizr/api/vendor/slim/slim/Slim/MiddlewareDispatcher.php(147): Slim\\Middleware\\RoutingMiddleware->process()","#14 /config/www/organizr/api/vendor/slim/slim/Slim/Middleware/ErrorMiddleware.php(107): Psr\\Http\\Server\\RequestHandlerInterface@anonymous\u0000/config/www/organizr/api/vendor/slim/slim/Slim/MiddlewareDispatcher.php:128$1e9a->handle()","#15 /config/www/organizr/api/vendor/slim/slim/Slim/MiddlewareDispatcher.php(147): Slim\\Middleware\\ErrorMiddleware->process()","#16 /config/www/organizr/api/v2/index.php(92): Psr\\Http\\Server\\RequestHandlerInterface@anonymous\u0000/config/www/organizr/api/vendor/slim/slim/Slim/MiddlewareDispatcher.php:128$1e9a->handle()","#17 /config/www/organizr/api/vendor/slim/slim/Slim/MiddlewareDispatcher.php(313): {closure}()","#18 /config/www/organizr/api/vendor/slim/slim/Slim/MiddlewareDispatcher.php(81): Psr\\Http\\Server\\RequestHandlerInterface@anonymous\u0000/config/www/organizr/api/vendor/slim/slim/Slim/MiddlewareDispatcher.php:294$1e9c->handle()","#19 /config/www/organizr/api/vendor/slim/slim/Slim/App.php(215): Slim\\MiddlewareDispatcher->handle()","#20 /config/www/organizr/api/vendor/slim/slim/Slim/App.php(199): Slim\\App->handle()","#21 /config/www/organizr/api/v2/index.php(151): Slim\\App->run()"]}}
```

**Comment by causefx** [comment]
it seems update didnt go thru...
can you grab the apikey...  then goto https://organizr-address/api/v2/update/migrate/2.1.2200?apikey=apikey-here

**Comment by alesnav** [comment]
It does not allow me to authenticate, so I receive this error:

```
{
    "response": {
        "result": "error",
        "message": "Not Authorized",
        "data": null
    }
}
```

**Comment by causefx** [comment]
thats even with your API key from data/config.php?

the key is under `organizrAPI`

**Comment by alesnav** [comment]
Ok, I have located it inside config.php file (changed value to ***):

```
# cat config.php | grep -i organizrAPI
        'organizrAPI' => '***',
```


-----------

LOL, sorry about that, I didn't see the "apikey-here" parameter in your note xD

Ok, this is the output:

```
{
    "response": {
        "result": "success",
        "message": "Ran update function for version: 2.1.2200",
        "data": {
            "total_size": "164.20 kB",
            "total_files": 4,
            "files": [
                {
                    "name": "backup[2024-01-05_22-38 - 85][2.1.2460].zip",
                    "size": "49 kB",
                    "date": "2024-01-05T22:38:56Z"
                },
                {
                    "name": "backup[2022-06-19_01-04 - NH][2.1.2330].zip",
                    "size": "44 kB",
                    "date": "2022-06-19T01:04:58Z"
                },
                {
                    "name": "backup[2021-09-19_21-05][2.1.655].zip",
                    "size": "37 kB",
                    "date": "2021-09-19T21:05:46Z"
                },
                {
                    "name": "backup[2021-05-24_14-03][2.1.308].zip",
                    "size": "35 kB",
                    "date": "2021-05-24T14:03:03Z"
                }
            ]
        }
    }
}
```

**Comment by alesnav** [comment]
Ah nice, that action has fixed everything and now it is up and working!!

Thank you so much!!

**Comment by causefx** [comment]
sweet. glad it's sorted.
