### ISSUE TITLE
Slim Application Error

### ISSUE THREAD

**Issue by CheekyPanda2** [causefx/Organizr#2010]
###### Operating System: Windows/MacOS/Ubuntu
<hr>

##### Problem Description:

I'm receiving this error when I open organizr,

Webserver Error:
Slim Application Error
The application could not run because of the following error:

Details
Type: TypeError
Code: 0
Message: array_map(): Argument #2 ($array) must be of type array, null given
File: /config/www/organizr/api/classes/organizr.class.php
Line: 4214

<hr>

##### Reproduction Steps:

<hr>

#### Errors on screen?  If so paste here:

```
#0 /config/www/organizr/api/classes/organizr.class.php(4214): array_map()
#1 /config/www/organizr/api/v2/routes/root.php(68): Organizr->getUserTabsAndCategories()
#2 /config/www/organizr/api/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(43): {closure}()
#3 /config/www/organizr/api/vendor/slim/slim/Slim/Routing/Route.php(384): Slim\Handlers\Strategies\RequestResponse->__invoke()
#4 /config/www/organizr/api/vendor/slim/slim/Slim/MiddlewareDispatcher.php(81): Slim\Routing\Route->handle()
#5 /config/www/organizr/api/vendor/slim/slim/Slim/MiddlewareDispatcher.php(81): Slim\MiddlewareDispatcher->handle()
#6 /config/www/organizr/api/vendor/slim/slim/Slim/Routing/Route.php(341): Slim\MiddlewareDispatcher->handle()
#7 /config/www/organizr/api/vendor/slim/slim/Slim/Routing/RouteRunner.php(84): Slim\Routing\Route->run()
#8 /config/www/organizr/api/vendor/slim/slim/Slim/Middleware/RoutingMiddleware.php(59): Slim\Routing\RouteRunner->handle()
#9 /config/www/organizr/api/vendor/slim/slim/Slim/MiddlewareDispatcher.php(147): Slim\Middleware\RoutingMiddleware->process()
#10 /config/www/organizr/api/vendor/slim/slim/Slim/Middleware/ErrorMiddleware.php(107): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#11 /config/www/organizr/api/vendor/slim/slim/Slim/MiddlewareDispatcher.php(147): Slim\Middleware\ErrorMiddleware->process()
#12 /config/www/organizr/api/v2/index.php(92): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#13 /config/www/organizr/api/vendor/slim/slim/Slim/MiddlewareDispatcher.php(313): {closure}()
#14 /config/www/organizr/api/vendor/slim/slim/Slim/MiddlewareDispatcher.php(81): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#15 /config/www/organizr/api/vendor/slim/slim/Slim/App.php(215): Slim\MiddlewareDispatcher->handle()
#16 /config/www/organizr/api/vendor/slim/slim/Slim/App.php(199): Slim\App->handle()
#17 /config/www/organizr/api/v2/index.php(151): Slim\App->run()
#18 {main}
```

**Comment by cbartondock** [comment]
Yo this is not fixed.
